version: "3.3"

networks:
  production-network:
    driver: bridge

services:
  #  app:
  #  image:
  frontend:
    image: nginx:latest
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - MY_DOMAIN=dev.local
    volumes:
      - ../src/main/java/site:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx:/etc/nginx/conf.d
      #- ./nginx/certbot/conf:/etc/letsencrypt
      #- ./nginx/certbot/www:/var/www/certbot
    container_name: frontend-nginx
    ports:
      - "80:80"
    #      - "443:443"
    networks:
      - production-network
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
